language: cpp
script: 
  - ./travis.sh
compiler:
  - gcc
# - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6.1" CC="gcc-6.1"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6.1
    - g++-6.1
    - hdf5
#   - clang
#   - libhdf5-serial-1.8.4
notifications:
  email: false
sudo: false
