language: cpp
script: 
  - ./travis.sh
compiler:
  - gcc
# - clang
install:
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - hdf5
#   - clang
#   - libhdf5-serial-1.8.4
notifications:
  email: false
sudo: false
